CREATE table autores(
id_autor INT generated by default as identity primary key, 
nombre VARCHAR(100), 
biografia VARCHAR(1000), 
fecha_de_nacimiento DATE,
mail VARCHAR(100) unique, 
contraseña VARCHAR(100), 
puntuacion_promedio_de_obras INT, 
fecha_ingreso DATE default CURRENT_DATE, 
pais VARCHAR(50), 
foto_perfil VARCHAR
);


CREATE table comentarios(
id_comentarios INT generated by default as identity primary key, 
id_usuario INT references autores(id_autor), 
estrellas INT not null constraint check_estrellas check (estrellas >=0 and estrellas <=5), 
fecha_de_publicacion DATE default CURRENT_DATE, 
contenido_comentario VARCHAR(500)
);

CREATE table obras(
id_obras INT generated by default as identity primary key, 
titulo VARCHAR(200) not null, 
portada VARCHAR,
descripcion VARCHAR(1000) not null, 
id_tag INT unique,
id_autor INT references autores(id_autor),
fecha_de_publicacion DATE default CURRENT_DATE,
puntuacion INT not null constraint check_puntuacion check (puntuacion >=0 and puntuacion <=5),
contenido VARCHAR not null
);

create table tag(
id_tag INT generated by default as identity primary key,
id_obra INT not null,
romance INT,
fantasia INT,
accion INT,
misterio INT,
suspenso INT,
aventura INT,
terror INT,
ficcion INT,
ciencia_ficcion INT,
humor INT,
poemas/poesia INT,
relatos_breves INT,
sobrenatural/paranormal INT,
)


